num = int(input())



for i in range(num):
    n = int(input())
    


    if n == 1:
        print('##')
        print('##')

    if n == 2:
        a = '##..'
        b = '..##'
        print(a)
        print(a)
        print(b)
        print(b)

    if n == 3:
        a = '##..##'
        b = '..##..'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)

    if n == 4:
        a = '##..##..'
        b = '..##..##'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)

    if n == 5:
        a = '##..##..##'
        b = '..##..##..'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)

    if n == 6:
        a = '##..##..##..'
        b = '..##..##..##'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)

    if n == 7:
        a = '##..##..##..##'
        b = '..##..##..##..'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)

    if n == 8:
        a = '##..##..##..##..'
        b = '..##..##..##..##'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)


    if n == 9:
        a = '##..##..##..##..##'
        b = '..##..##..##..##..'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)


    if n == 10:
        a = '##..##..##..##..##..'
        b = '..##..##..##..##..##'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)


    if n == 11:
        a = '##..##..##..##..##..##'
        b = '..##..##..##..##..##..'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
 

    if n == 12:
        a = '##..##..##..##..##..##..'
        b = '..##..##..##..##..##..##'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)


    if n == 13:
        a = '##..##..##..##..##..##..##'
        b = '..##..##..##..##..##..##..'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)

    if n == 14:  
        a = '##..##..##..##..##..##..##..'
        b = '..##..##..##..##..##..##..##'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)


    if n == 15:
        a = '##..##..##..##..##..##..##..##'
        b = '..##..##..##..##..##..##..##..'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)


    if n == 16:
        a = '##..##..##..##..##..##..##..##..'
        b = '..##..##..##..##..##..##..##..##'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)


    if n == 17:
        a = '##..##..##..##..##..##..##..##..##'
        b = '..##..##..##..##..##..##..##..##..'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)


    if n == 18:
        a = '##..##..##..##..##..##..##..##..##..'
        b = '..##..##..##..##..##..##..##..##..##'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)


    if n == 19:
        a = '##..##..##..##..##..##..##..##..##..##'
        b = '..##..##..##..##..##..##..##..##..##..'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)


    if n == 20:
        a = '##..##..##..##..##..##..##..##..##..##..'
        b = '..##..##..##..##..##..##..##..##..##..##'
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)
        print(a)
        print(a)
        print(b)
        print(b)








